[package]
name = "memory-lru"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT"
description = "A memory-based wrapper around the lru crate"

[dependencies]
lru = "0.8.0"
